name: Cypress
on:
  push:
    branches:
    - main
  schedule:
    - cron: "5/15 * * * *"
jobs:
  cypress-run:
    environment: cypress
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
      - name: The job has failed
        if: ${{ failure() }}
        uses: ShaunLWM/action-pushbullet@master
        env:
          PB_TOKEN: ${{ secrets.PB_TOKEN }}
          PB_TITLE: NHS Booking Check Failed!
          PB_TEXT: Can you book an appointment? "https://www.nhs.uk/conditions/coronavirus-covid-19/coronavirus-vaccination/book-coronavirus-vaccination/"
    env:
      CYPRESS_NHS_NUMBER: ${{ secrets.CYPRESS_NHS_NUMBER }}
      CYPRESS_DOB_DAY: ${{ secrets.CYPRESS_DOB_DAY }}
      CYPRESS_DOB_MONTH: ${{ secrets.CYPRESS_DOB_MONTH }}
      CYPRESS_DOB_YEAR: ${{ secrets.CYPRESS_DOB_YEAR }}
